name: Run tests

on:
  push:
    branches:
      - ovelse/answer/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          version: 17.x

      - run: npm ci
      - run: npm verify
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}